CREATE OR REPLACE TABLE ECOMMERCE.RAW.OLIST_CUSTOMERS (
  customer_id VARCHAR,
  customer_unique_id VARCHAR,
  customer_zip_code_prefix VARCHAR,
  customer_city VARCHAR,
  customer_state VARCHAR
);

CREATE OR REPLACE TABLE ECOMMERCE.RAW.OLIST_GEOLOCATION (
  GEOLOCATION_ZIP_CODE_PREFIX  VARCHAR,
  GEOLOCATION_LAT              VARCHAR,
  GEOLOCATION_LNG              VARCHAR,
  GEOLOCATION_CITY             VARCHAR,
  GEOLOCATION_STATE            VARCHAR
);

CREATE OR REPLACE TABLE ECOMMERCE.RAW.OLIST_ORDERS (
  ORDER_ID                        VARCHAR,
  CUSTOMER_ID                     VARCHAR,
  ORDER_STATUS                    VARCHAR,
  ORDER_PURCHASE_TIMESTAMP        VARCHAR,
  ORDER_APPROVED_AT               VARCHAR,
  ORDER_DELIVERED_CARRIER_DATE    VARCHAR,
  ORDER_DELIVERED_CUSTOMER_DATE   VARCHAR,
  ORDER_ESTIMATED_DELIVERY_DATE   VARCHAR
);


CREATE OR REPLACE TABLE ECOMMERCE.RAW.OLIST_ORDER_ITEMS (
  ORDER_ID            VARCHAR,
  ORDER_ITEM_ID       VARCHAR,
  PRODUCT_ID          VARCHAR,
  SELLER_ID           VARCHAR,
  SHIPPING_LIMIT_DATE VARCHAR,
  PRICE               VARCHAR,
  FREIGHT_VALUE       VARCHAR
);


CREATE OR REPLACE TABLE ECOMMERCE.RAW.OLIST_ORDER_PAYMENTS (
  ORDER_ID             VARCHAR,
  PAYMENT_SEQUENTIAL   VARCHAR,
  PAYMENT_TYPE         VARCHAR,
  PAYMENT_INSTALLMENTS VARCHAR,
  PAYMENT_VALUE        VARCHAR
);

CREATE OR REPLACE TABLE ECOMMERCE.RAW.OLIST_ORDER_REVIEWS (
  REVIEW_ID                 VARCHAR,
  ORDER_ID                  VARCHAR,
  REVIEW_SCORE              VARCHAR,
  REVIEW_COMMENT_TITLE      VARCHAR,
  REVIEW_COMMENT_MESSAGE    VARCHAR,
  REVIEW_CREATION_DATE      VARCHAR,
  REVIEW_ANSWER_TIMESTAMP   VARCHAR
);


CREATE OR REPLACE TABLE ECOMMERCE.RAW.OLIST_PRODUCTS (
  PRODUCT_ID                    VARCHAR,
  PRODUCT_CATEGORY_NAME         VARCHAR,
  PRODUCT_NAME_LENGHT           VARCHAR,
  PRODUCT_DESCRIPTION_LENGHT    VARCHAR,
  PRODUCT_PHOTOS_QTY            VARCHAR,
  PRODUCT_WEIGHT_G              VARCHAR,
  PRODUCT_LENGTH_CM             VARCHAR,
  PRODUCT_HEIGHT_CM             VARCHAR,
  PRODUCT_WIDTH_CM              VARCHAR
);


CREATE OR REPLACE TABLE ECOMMERCE.RAW.OLIST_SELLERS (
  SELLER_ID               VARCHAR,
  SELLER_ZIP_CODE_PREFIX  VARCHAR,
  SELLER_CITY             VARCHAR,
  SELLER_STATE            VARCHAR
);

CREATE OR REPLACE TABLE ECOMMERCE.RAW.PRODUCT_CATEGORY_NAME_TRANSLATION (
  PRODUCT_CATEGORY_NAME           VARCHAR,
  PRODUCT_CATEGORY_NAME_ENGLISH   VARCHAR
);