--------- DBT ROLE
CREATE ROLE IF NOT EXISTS DBT_ROLE;

-- GIVING ACCESS TO WAREHOUSE
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;

-- GIVING CONTROL OVER DATABASE FOR SCHEMA CREATION
GRANT USAGE ON DATABASE ECOMMERCE TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE ECOMMERCE TO ROLE DBT_ROLE;

-- GIVING ACCESS TO RAW SCHEMA FOR READING
GRANT USAGE ON SCHEMA ECOMMERCE.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE.RAW TO ROLE DBT_ROLE;

GRANT ROLE DBT_ROLE TO USER federicogarland1;



--------- ANALYTICS ROLE 
CREATE ROLE IF NOT EXISTS ANALYTICS_ROLE;

-- GIVING ACCESS TO WAREHOUSE
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYTICS_ROLE;

-- GIVING ACCESS TO DATABASE AND MARTS SCHEMA FOR READING
GRANT USAGE ON DATABASE ECOMMERCE TO ROLE ANALYTICS_ROLE;

GRANT USAGE ON SCHEMA ECOMMERCE.MARTS TO ROLE ANALYTICS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE.MARTS TO ROLE ANALYTICS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE.MARTS TO ROLE ANALYTICS_ROLE;

GRANT ROLE ANALYTICS_ROLE TO USER federicogarland1;
