CREATE WAREHOUSE IF NOT EXISTS DBT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = true;

 CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = true; 

CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH 
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60 
  AUTO_RESUME = true 
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 3
  SCALING_POLICY = ECONOMY

CREATE DATABASE IF NOT EXISTS ECOMMERCE;

CREATE SCHEMA IF NOT EXISTS ECOMMERCE.RAW;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE.STAGING;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE.MARTS;


