CREATE WAREHOUSE IF NOT EXISTS DBT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = true;

 CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = true; 

CREATE DATABASE IF NOT EXISTS ECOMMERCE;

CREATE SCHEMA IF NOT EXISTS ECOMMERCE.RAW;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE.STAGING;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE.MARTS;
